export const SET_SEARCH_PHRASE = "SET_SEARCH_PHRASE";
export const SET_REPLACE_WITH_PHRASE = "SET_REPLACE_WITH_PHRASE";

export const SEARCH_WIKI_ARTICLES_FETCH = "SEARCH_WIKI_ARTICLES_FETCH";
export const SEARCH_WIKI_ARTICLES_ERROR = "SEARCH_WIKI_ARTICLES_ERROR";
export const SEARCH_WIKI_ARTICLES_SUCCESS = "SEARCH_WIKI_ARTICLES";